---
# Copyright 2016 IBM Corp.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file describes the configuration for a private compute cloud.
# It features three controller nodes, compute nodes, and Ceph OSD nodes.

version: 1.0

reference-architecture:
    - private-compute-cloud

ipaddr-mgmt-network: 192.168.16.0/20
ipaddr-mgmt-switch:
    rack1: 192.168.16.20
ipaddr-data-switch:
    rack1: 192.168.16.25
redundant-network: false
userid-default: user
password-default: passw0rd
userid-mgmt-switch: user        # applied to all mgmt switches
password-mgmt-switch: passw0rd  # applied to all mgmt switches
userid-data-switch: user
password-data-switch: passw0rd
internal-floating-ipaddr: 172.29.236.50
external-floating-ipaddr: 10.0.16.50
networks:
    external1:
        description: Organization site or external network
        addr: 10.0.16.0/22
        # Note you can uncomment the following section to provide a set of IPs
        # on this network that will be allocated to the hosts.  The default
        # behavior is to allocate from the full subnet.
        # available-ips:
            # - 10.0.16.20
            # - 10.0.16.35
            # - 10.0.16.106 10.0.16.110  # this is an IP range
            # - 10.0.16.115
        broadcast: 10.0.16.255
        gateway: 10.0.16.1
        dns-nameservers: 10.0.16.200
        dns-search: mycompany.domain.com
        method: static
        eth-port: eth10
        mtu: 9000
    external2:
        description: Interface for eth11
        method: manual
        eth-port: eth11
    pxe-dhcp:
        description: Change pxe port(eth15) to dhcp
        method: dhcp
        eth-port: eth15
    openstack-mgmt:
        description: OpenStack Management Network
        bridge: br-mgmt
        method: static
        tcp_segmentation_offload: 'off'
        addr: 172.29.236.0/22
        vlan: 10
        eth-port: eth10
    openstack-stg:
        description: OpenStack Storage Network
        bridge: br-storage
        method: static
        tcp_segmentation_offload: 'off'
        addr: 172.29.244.0/22
        vlan: 20
        eth-port: eth10
    openstack-tenant-vxlan:
        description: OpenStack Tenant vxlan Network
        bridge: br-vxlan
        method: static
        addr: 172.29.240.0/22
        vlan: 30
        eth-port: eth11
    openstack-tenant-vlan:
        description: OpenStack Tenant vlan Network
        bridge: br-vlan
        method: static
        addr: 0.0.0.0/1  # Nodes do not get IPs assigned in this network
        eth-port: eth11
        bridge-port: veth12
    ceph-replication:
        description: Ceph Replication Network
        addr: 172.29.248.0/22
        bridge: br-replication
        method: static
        vlan: 40
        eth-port: eth11
racks:
    - rack-id: rack1
      data-center: dataeast
      room: room33
      row: row1
node-templates:
    controllers:
        hostname: controller
        userid-ipmi: userid
        password-ipmi: password
        cobbler-profile: ubuntu-14.04.5-server-amd64.sm
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
        # Each host has one network interface for each of these ports and
        # these port numbers represent the switch port number to which the host
        # interface is cabled.  If a port can be broken out using breakout
        # cables, then this would be specified as '- <port>/<sub-port>'.
        # To add or remove hosts for this node-template you add or remove
        # switch port numbers to these ports.
        ports:
            pxe:
                rack1:
                    - 1
                    - 2
                    - 3
            ipmi:
                rack1:
                    - 4
                    - 5
                    - 6
            eth10:
                rack1:
                    - 1
                    - 2
                    - 3
            eth11:
                rack1:
                    - 4
                    - 5
                    - 6
        networks:
            - openstack-mgmt
            - openstack-stg
            - openstack-tenant-vlan
            - openstack-tenant-vxlan
            - external1
            - external2
            - pxe-dhcp
    compute:
        hostname: compute
        userid-ipmi: userid
        password-ipmi: password
        cobbler-profile: ubuntu-14.04.5-server-ppc64el
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
        # Each host has one network interface for each of these ports and
        # these port numbers represent the switch port number to which the host
        # interface is cabled.  If a port can be broken out using breakout
        # cables, then this would be specified as '- <port>/<sub-port>'.
        # To add or remove hosts for this node-template you add or remove
        # switch port numbers to these ports.
        ports:
            pxe:
                rack1:
                    - 7
                    - 8
                    - 9
            ipmi:
                rack1:
                    - 10
                    - 11
                    - 12
            eth10:
                rack1:
                    - 7
                    - 8
                    - 9
            eth11:
                rack1:
                    - 10
                    - 11
                    - 12
        networks:
            - openstack-mgmt
            - openstack-stg
            - openstack-tenant-vlan
            - openstack-tenant-vxlan
            - external1
            - external2
            - pxe-dhcp
    ceph-osd:
        hostname: cephosd
        userid-ipmi: userid
        password-ipmi: password
        cobbler-profile: ubuntu-14.04.5-server-ppc64el
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
        # Each host has one network interface for each of these ports and
        # these port numbers represent the switch port number to which the host
        # interface is cabled.  If a port can be broken out using breakout
        # cables, then this would be specified as '- <port>/<sub-port>'.
        # To add or remove hosts for this node-template you add or remove
        # switch port numbers to these ports.
        ports:
            pxe:
                rack1:
                    - 13
                    - 14
                    - 15
            ipmi:
                rack1:
                    - 16
                    - 17
                    - 18
            eth10:
                rack1:
                    - 13
                    - 14
                    - 15
            eth11:
                rack1:
                    - 16
                    - 17
                    - 18
        networks:
            - external1
            - external2
            - openstack-mgmt
            - openstack-stg
            - ceph-replication
            - pxe-dhcp
        journal-devices:
            - /dev/sdc
            - /dev/sdd
        osd-devices:
            - /dev/sde
            - /dev/sdf
            - /dev/sdg
            - /dev/sdh

software-bootstrap-hosts: controllers[0]  # Select first 'controllers' node
software-bootstrap-cmd: |
    set -o pipefail
    apt-get -y update >/dev/null 2>&1
    type git >/dev/null 2>&1
    if [ $? != 0 ]; then
        apt-get install -qq -y git
    fi
    if [ ! -d os-services ]; then
        git clone git://github.com/open-power-ref-design/os-services.git
    fi
    cd os-services
    git checkout v1.0.0
    export DEPLOY_CEPH=yes
    export DEPLOY_OPSMGR=yes
    # export ANSIBLE_HOST_KEY_CHECKING=False
    ./scripts/bootstrap-cluster.sh | tee -a ../bootstrap-cluster.out
    rc=$?
    if [ $rc != 0 ]; then
        echo "./scripts/bootstrap-cluster.sh failed, rc=$rc"
        exit $rc
    fi
    HOST=`hostname -A`
    echo ""
    echo "The deployment should now be continued on the first controller node"
    echo "Please log into $HOST and complete the installation"
    echo ""
    echo "ssh ubuntu@$HOST"
    echo "sudo su"
    echo "cd ~/os-services"
