---
# Copyright 2017 IBM Corp.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: activate_client_interfaces.yml
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather facts
      setup:
    - name: Bring down all interfaces except ansible communication interface
      command: "ip link set dev {{ item }} down"
      when:
        - "{{ item != 'lo' }}"
        - "{{ inventory_hostname != \
           hostvars[inventory_hostname]['ansible_' + \
           item.replace('-', '_')].get('ipv4', {}).get('address') }}"
        - "{{ hostvars[inventory_hostname]['ansible_' + \
           item.replace('-', '_')]['active'] }}"
      with_items: "{{ ansible_interfaces }}"

    # A one time copy is made of the network interfaces files after initial
    # OS install. This is now attempted at the end of install in wait_for_
    # client_ping.yml, but is re-attempted here for previous installs done
    # with prior versions of Genesis.

    - block:
        - name: Check if deploy t0 interfaces file exists
          stat: path=/etc/network/interfaces.gen-deploy-t0
          register: st

        - name: One time copy t0 interfaces file
          command: "cp /etc/network/interfaces /etc/network/interfaces.gen-deploy-t0"
          when: not st.stat.exists

        - name: Backup interfaces file
          command: "cp /etc/network/interfaces /etc/network/interfaces.bak"

        - name: Write interfaces file for ipv6 auto on all interfaces if Ubuntu
          template:
            src: "{{ playbook_dir }}/templates/ipv6Interface_ubuntu.j2"
            dest: /etc/network/interfaces
            owner: "root"
            group: "root"
            mode: "0644"
      when: ansible_distribution == 'Ubuntu'

    - name: Write ifcfg files for ipv6 on all interfaces if RHEL/CentOS
      template:
        src: "{{ playbook_dir }}/templates/ipv6Interface_rhel.j2"
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item }}"
        owner: "root"
        group: "root"
        mode: "0644"
      when: (ansible_distribution == 'CentOS') or
            (ansible_distribution == 'RedHat')
      with_items: "{{ ansible_interfaces }}"

    - name: Bring up all interfaces
      command: "ip link set dev {{ item }} up"
      when:
        - "{{ item != 'lo' }}"
        - "{{ inventory_hostname != hostvars[inventory_hostname]['ansible_' + \
           item.replace('-', '_')].get('ipv4', {}).get('address') }}"
      with_items: "{{ ansible_interfaces }}"
      ignore_errors: yes
