---
- name: Install software
  hosts: all
  vars_files:
    - /home/user/power-up/playbooks/poweraie_software.yml
  tasks:
    - name: install "{{ item }}"
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ all.packages }}"
